# ~/.bashrc: 
#
# configurations for interactive Bash usage:
# - aliases
# - favorite editor
# - config the bash prompt

# - executed by bash for (interactive) non-login shells.
# - but also executed by bash for (non-interactive) login shells.
# - see /usr/share/doc/bash/examples/startup-files (in the package bash-doc) for examples
#
if [ -r "$HOME/.profile" ]; then
    . "$HOME/.profile"
else
    echo "Warn: could not load ~/.profile" >&2
fi

case "$-" in
    *i*) [ -r "$HOME/.config/profile/setup-loader.bash" ] && . "$HOME/.config/profile/setup-loader.bash" ;;
    *)
        # non-interactive login shell
            return 
        ;;
esac
